In [22]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ziyo\appdata\local\programs\python\python312\lib\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\ziyo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.3.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ziyo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ziyo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ziyo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [27]:
df_1 = pd.read_csv('df_types.csv')

In [3]:
df_1.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00

In [4]:
df_1.isna().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year               36
manufacturer        0
model             128
fuel               63
odometer            0
title_status      166
transmission       45
image_url           2
description         2
state               0
lat                98
long               98
posting_date        2
price_category      0
date                2
dtype: int64

In [5]:
(df_1.isna().sum()).sort_values(ascending=False)

title_status      166
model             128
long               98
lat                98
fuel               63
transmission       45
year               36
posting_date        2
description         2
image_url           2
date                2
url                 0
odometer            0
manufacturer        0
state               0
price               0
region_url          0
region              0
price_category      0
id                  0
dtype: int64

In [6]:
df_1['title_status'].value_counts(dropna=False)

title_status
clean         9518
rebuilt        171
NaN            166
salvage         92
lien            35
missing         16
parts only       2
Name: count, dtype: int64

In [7]:
df_1[df_1['title_status'].isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
11,7316540706,https://cincinnati.craigslist.org/ctd/d/fairfi...,cincinnati,https://cincinnati.craigslist.org,4995,2012.0,fiat,500 pop,gas,59242,NaN,manual,https://images.craigslist.org/00Z0Z_jbUmVcYlwR...,"2012 Fiat 500 Pop FOR ONLY $102/mo!59,242 mi. ...",oh,39.297045,-84.563243,2021-05-03T21:03:32-0400,low,2021-05-04 01:03:32+00:00
187,7313570594,https://orangecounty.craigslist.org/ctd/d/coro...,orange county,https://orangecounty.craigslist.org,17900,2013.0,ram,1500 tradesman quad cab,gas,145499,NaN,automatic,https://images.craigslist.org/00H0H_1JFMPCYyW8...,2013 Ram 1500 Tradesman Quad Cab PRICED TO SEL...,ca,33.873436,-117.542806,2021-04-27T15:03:47-0700,medium,2021-04-27 22:03:47+00:00
245,7315211652,https://ocala.craigslist.org/ctd/d/riverview-2...,ocala,https://ocala.craigslist.org,40990,2019.0,toyota,sienna xle,gas,3700,NaN,automatic,https://images.craigslist.org/01111_grKNF8GrXz...,2019 Toyota Sienna - Wheelchair Accessible Han...,fl,27.849760,-82.364950,2021-05-01T06:35:56-0400,high,2021-05-01 10:35:56+00:00
286,7306702976,https://toledo.craigslist.org/ctd/d/chelsea-73...,toledo,https://toledo.craigslist.org,4592,2003.0,chevrolet,avalanche 1500,gas,268691,NaN,automatic,https://images.craigslist.org/00808_1IOMJuA4GL...,$73/mo - 2003 Chevrolet Avalanche 1500 BaseCre...,oh,42.300673,-84.024108,2021-04-14T12:03:01-0400,low,2021-04-14 16:03:01+00:00
312,7307609203,https://roseburg.craigslist.org/ctd/d/eugene-2...,roseburg,https://roseburg.craigslist.org,18450,2017.0,ford,mustang,gas,66049,NaN,automatic,https://images.craigslist.org/00505_4apF36sLbP...,"2017 Ford MUSTANG - $18,450 \tMayberry Motors ...",or,44.058499,-123.106176,2021-04-16T04:06:29-0700,medium,2021-04-16 11:06:29+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9740,7301707830,https://tricities.craigslist.org/ctd/d/bristol...,tri-cities,https://tricities.craigslist.org,8995,2013.0,honda,odyssey,gas,203112,NaN,automatic,https://images.craigslist.org/00u0u_bawW7HN8xW...,"2013 *Honda* *Odyssey* 5dr EX Van FWD - $8,995...",tn,36.541821,-82.234645,2021-04-04T13:12:27-0400,low,2021-04-04 17:12:27+00:00
9805,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,NaN,95674,NaN,NaN,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low,2021-04-28 18:25:32+00:00
9840,7314987181,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,20900,2014.0,lexus,rx 350,gas,70800,NaN,automatic,https://images.craigslist.org/00Q0Q_cGablAkoYV...,2014 *Lexus* *RX 350* 2014 LEXUS RX 350 SUV 1-...,tn,36.138022,-86.732261,2021-04-30T15:00:48-0500,medium,2021-04-30 20:00:48+00:00
9856,7309717260,https://savannah.craigslist.org/ctd/d/jacksonv...,savannah / hinesville,https://savannah.craigslist.org,11495,2006.0,lexus,gx 470,gas,242000,NaN,automatic,https://images.craigslist.org/00s0s_8xg4gw6aAg...,"2006 *Lexus* *GX 470* 4dr SUV 4WD - $11,495By ...",ga,30.513566,-81.621875,2021-04-20T08:01:49-0400,medium,2021-04-20 12:01:49+00:00
9981,7315557731,https://minneapolis.craigslist.org/csw/ctd/d/d...,minneapolis / st paul,https://minneapolis.craigslist.org,38943,2008.0,ford,f750 super duty - 55ft,diesel,81214,NaN,automatic,https://images.craigslist.org/00y0y_5jr8fQlu7e...,2008 Ford F750 F 750 F-750 Super Duty 55ft 55 ...,mn,45.082884,-94.334760,2021-05-01T18:03:06-0500,high,2021-05-01 23:03:06+00:00

In [28]:
df_1 = df_1.fillna({'title_status': 'other'})

In [9]:
(df_1.isna().sum()).sort_values(ascending=False)

model             128
long               98
lat                98
fuel               63
transmission       45
year               36
date                2
image_url           2
posting_date        2
description         2
price_category      0
state               0
id                  0
url                 0
odometer            0
manufacturer        0
price               0
region_url          0
region              0
title_status        0
dtype: int64

In [29]:
df_1 = df_1.fillna({'model': 'other'})

In [11]:
(df_1.isna().sum()).sort_values(ascending=False)

long              98
lat               98
fuel              63
transmission      45
year              36
date               2
posting_date       2
description        2
image_url          2
price_category     0
state              0
id                 0
url                0
odometer           0
model              0
manufacturer       0
price              0
region_url         0
region             0
title_status       0
dtype: int64

In [12]:
((df_1.isna().sum()) / len(df_1) * 100).sort_values(ascending=False)

long              0.98
lat               0.98
fuel              0.63
transmission      0.45
year              0.36
date              0.02
posting_date      0.02
description       0.02
image_url         0.02
price_category    0.00
state             0.00
id                0.00
url               0.00
odometer          0.00
model             0.00
manufacturer      0.00
price             0.00
region_url        0.00
region            0.00
title_status      0.00
dtype: float64

In [13]:
df_1[df_1['long'].isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
118,7312692841,https://tricities.craigslist.org/ctd/d/bmw-ser...,tri-cities,https://tricities.craigslist.org,17998,2012.0,bmw,5 series,gas,62665,clean,automatic,https://images.craigslist.org/00909_57Xyuj8AJH...,2012 BMW 5 Series 535i M Sport Heat & Cool Sea...,tn,NaN,NaN,2021-04-26T04:28:35-0400,medium,2021-04-26 08:28:35+00:00
126,7315526339,https://newjersey.craigslist.org/ctd/d/look-wh...,north jersey,https://newjersey.craigslist.org,22995,2014.0,bmw,7 series,gas,81085,clean,automatic,https://images.craigslist.org/00k0k_38TNTakyUf...,2014 BMW 7 Series 4dr Sdn 750Li xDrive AWD Aut...,nj,NaN,NaN,2021-05-01T17:49:09-0400,high,2021-05-01 21:49:09+00:00
502,7308641593,https://winstonsalem.craigslist.org/ctd/d/ford...,winston-salem,https://winstonsalem.craigslist.org,20998,2016.0,ford,transit cargo,gas,123825,clean,automatic,https://images.craigslist.org/00101_gwJT4WBNRo...,2016 Ford Transit Cargo Vans Work Van High Roo...,nc,NaN,NaN,2021-04-18T04:43:46-0400,medium,2021-04-18 08:43:46+00:00
567,7309282242,https://onslow.craigslist.org/ctd/d/mercedes-b...,jacksonville,https://onslow.craigslist.org,10810,2014.0,mercedes-benz,c-class,gas,124476,clean,automatic,https://images.craigslist.org/01414_6jNHxQwrKx...,2014 Mercedes Benz C Class C 250 Sport Coupe C...,nc,NaN,NaN,2021-04-19T12:06:28-0400,medium,2021-04-19 16:06:28+00:00
692,7314847134,https://atlanta.craigslist.org/atl/ctd/d/2008-...,atlanta,https://atlanta.craigslist.org,17900,2008.0,toyota,tundra,gas,96000,clean,automatic,https://images.craigslist.org/01313_6u7l4KgvV4...,Description: 2008 Toyota Tundra 5...,ga,NaN,NaN,2021-04-30T12:09:49-0400,medium,2021-04-30 16:09:49+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9388,7208549803,https://bellingham.craigslist.org/ctd/d/bellin...,bellingham,https://bellingham.craigslist.org,11999,NaN,other,other,NaN,95674,other,NaN,NaN,NaN,wa,NaN,NaN,NaN,medium,NaN
9408,7311736404,https://raleigh.craigslist.org/ctd/d/lexus-nx-...,raleigh / durham / CH,https://raleigh.craigslist.org,28998,2018.0,lexus,nx 300,gas,19863,clean,automatic,https://images.craigslist.org/00Q0Q_j7S3aRy6Sw...,2018 Lexus NX 300 Navigation Sunroof Bluetooth...,nc,NaN,NaN,2021-04-24T00:54:33-0400,high,2021-04-24 04:54:33+00:00
9650,7315596665,https://newjersey.craigslist.org/ctd/d/wow-201...,north jersey,https://newjersey.craigslist.org,16495,2013.0,jeep,grand cherokee,other,90878,clean,automatic,https://images.craigslist.org/00v0v_awwo3NjD7Q...,2013 Jeep Grand Cherokee 4WD 4dr Laredo Automa...,nj,NaN,NaN,2021-05-01T20:53:57-0400,medium,2021-05-02 00:53:57+00:00
9668,7308677951,https://myrtlebeach.craigslist.org/ctd/d/ford-...,myrtle beach,https://myrtlebeach.craigslist.org,33647,2015.0,ford,f-250 super duty,diesel,153524,clean,automatic,https://images.craigslist.org/00f0f_1c0aGXmmCL...,2015 Ford F250 4x4 Truck Diesel Pickup Trucks ...,sc,NaN,NaN,2021-04-18T08:43:25-0400,high,2021-04-18 12:43:25+00:00
9915,7312622931,https://cincinnati.craigslist.org/cto/d/2005-d...,cincinnati,https://cincinnati.craigslist.org,7999,2005.0,ford,excursion 2005,diesel,210000,clean,automatic,https://images.craigslist.org/00E0E_i9lrp2qCVK...,Largest sport utility vehicle ever made in the...,oh,NaN,NaN,2021-04-25T21:12:31-0400,low,2021-04-26 01:12:31+00:00

In [30]:
df_1 = df_1.dropna(subset=['long'])
df_1 = df_1.dropna(subset=['lat'])
df_1 = df_1.dropna(subset=['fuel'])
df_1 = df_1.dropna(subset=['transmission'])
df_1 = df_1.dropna(subset=['year'])
df_1 = df_1.dropna(subset=['date'])
df_1 = df_1.dropna(subset=['posting_date'])
df_1 = df_1.dropna(subset=['description'])
df_1 = df_1.dropna(subset=['image_url'])

In [15]:
((df_1.isna().sum()) / len(df_1) * 100).sort_values(ascending=False)

id                0.0
url               0.0
price_category    0.0
posting_date      0.0
long              0.0
lat               0.0
state             0.0
description       0.0
image_url         0.0
transmission      0.0
title_status      0.0
odometer          0.0
fuel              0.0
model             0.0
manufacturer      0.0
year              0.0
price             0.0
region_url        0.0
region            0.0
date              0.0
dtype: float64

In [16]:
df_1.info

<bound method DataFrame.info of               id                                                url  \
0     7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...
2     7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...
3     7308210929  https://fayetteville.craigslist.org/ctd/d/rale...
4     7316474668  https://newyork.craigslist.org/lgi/cto/d/baldw...
5     7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...
...          ...                                                ...
9995  7304876387  https://chautauqua.craigslist.org/ctd/d/falcon...
9996  7316152972  https://binghamton.craigslist.org/ctd/d/roches...
9997  7310993818  https://salem.craigslist.org/ctd/d/salem-2011-...
9998  7306637427  https://madison.craigslist.org/ctd/d/madison-2...
9999  7311960763  https://norfolk.craigslist.org/ctd/d/chesapeak...

                       region                           region_url  price  \
0                 chattanooga   https://chattanooga.craigslist.org  54990
2                reno / tahoe          https://reno.craigslist.org  35590
3                fayetteville  https://fayetteville.craigslist.org  14500
4               new york city       https://newyork.craigslist.org  21800
5                   knoxville     https://knoxville.craigslist.org  14590
...                       ...                                  ...    ...
9995               chautauqua    https://chautauqua.craigslist.org   4495
9996               binghamton    https://binghamton.craigslist.org  14495
9997                    salem         https://salem.craigslist.org   8995
9998                  madison       https://madison.craigslist.org  31900
9999  norfolk / hampton roads       https://norfolk.craigslist.org  31990

        year manufacturer                      model    fuel  odometer  \
0     2020.0          ram     2500 crew cab big horn  diesel     27442
2     2017.0   volkswagen           golf r hatchback     gas     14048
3     2013.0       toyota                       rav4     gas    117291
4     2021.0       nissan                     altima     gas      8000
5     2012.0          bmw     1 series 128i coupe 2d   other     80465
...      ...          ...                        ...     ...       ...
9995  2002.0       toyota                       rav4     gas    150000
9996  2008.0         jeep                   wrangler     gas    113573
9997  2011.0         audi  a3 2.0t premium plus pzev     gas    150184
9998  2015.0      porsche                    cayenne  hybrid     61943
9999  2017.0          ram     1500 crew cab big horn     gas     35921

     title_status transmission  \
0           clean        other
2           clean        other
3           clean    automatic
4           clean    automatic
5           clean        other
...           ...          ...
9995        clean    automatic
9996        clean        other
9997        clean    automatic
9998        clean    automatic
9999        clean        other

                                              image_url  \
0     https://images.craigslist.org/00N0N_1xMPvfxRAI...
2     https://images.craigslist.org/00y0y_eeZjWeiSfb...
3     https://images.craigslist.org/00606_iGe5iXidib...
4     https://images.craigslist.org/00V0V_3pSOiPZ3Sd...
5     https://images.craigslist.org/00F0F_5UAXmOzC18...
...                                                 ...
9995  https://images.craigslist.org/00n0n_aaEBqmzz5Z...
9996  https://images.craigslist.org/00000_9ZNVdXaiei...
9997  https://images.craigslist.org/00X0X_k5JiZDDyqM...
9998  https://images.craigslist.org/00O0O_gBihGEQxYT...
9999  https://images.craigslist.org/00c0c_4rTlvLXy36...

                                            description state        lat  \
0     Carvana is the safer way to buy a car During t...    tn  35.060000
2     Carvana is the safer way to buy a car During t...    ca  33.779214
3     2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    nc  35.715954
4     2021 Nissan Altima Sv with Only 8 K Miles Titl...    ny  40.654800
5     Carvana is the safer way to buy a car During t...    tn  35.970000
...                                                 ...   ...        ...
9995  Transmission:Automatic Exterior Color:WHITE In...    ny  42.123900
9996  2008 Jeep Wrangler X  Offered by: R&L Auto -- ...    ny  43.216990
9997  2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...    or  44.925908
9998  2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...    wi  43.029559
9999  Carvana is the safer way to buy a car During t...    va  36.670000

            long              posting_date price_category  \
0     -85.250000  2021-04-17T12:30:50-0400           high
2     -84.411811  2021-04-28T03:52:20-0700           high
3     -78.655304  2021-04-17T10:08:57-0400         medium
4     -73.609700  2021-05-03T18:32:06-0400         medium
5     -83.940000  2021-04-08T15:10:56-0400         medium
...          ...                       ...            ...
9995  -79.189500  2021-04-10T16:33:57-0400            low
9996  -77.755610  2021-05-03T09:36:30-0400         medium
9997 -122.982753  2021-04-22T12:14:01-0700            low
9998  -89.397796  2021-04-14T09:14:42-0500           high
9999  -76.300000  2021-04-24T13:50:49-0400           high

                           date
0     2021-04-17 16:30:50+00:00
2     2021-04-28 10:52:20+00:00
3     2021-04-17 14:08:57+00:00
4     2021-05-03 22:32:06+00:00
5     2021-04-08 19:10:56+00:00
...                         ...
9995  2021-04-10 20:33:57+00:00
9996  2021-05-03 13:36:30+00:00
9997  2021-04-22 19:14:01+00:00
9998  2021-04-14 14:14:42+00:00
9999  2021-04-24 17:50:49+00:00

[9778 rows x 20 columns]>

In [17]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00
5,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012.0,bmw,1 series 128i coupe 2d,other,80465,clean,other,https://images.craigslist.org/00F0F_5UAXmOzC18...,Carvana is the safer way to buy a car During t...,tn,35.970000,-83.940000,2021-04-08T15:10:56-0400,medium,2021-04-08 19:10:56+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002.0,toyota,rav4,gas,150000,clean,automatic,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low,2021-04-10 20:33:57+00:00
9996,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008.0,jeep,wrangler,gas,113573,clean,other,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium,2021-05-03 13:36:30+00:00
9997,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011.0,audi,a3 2.0t premium plus pzev,gas,150184,clean,automatic,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low,2021-04-22 19:14:01+00:00
9998,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015.0,porsche,cayenne,hybrid,61943,clean,automatic,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high,2021-04-14 14:14:42+00:00
9999,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017.0,ram,1500 crew cab big horn,gas,35921,clean,other,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high,2021-04-24 17:50:49+00:00

In [41]:
df_1['price_category'].value_counts()

price_category
high      3409
low       3189
medium    3180
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

lben = LabelEncoder()

lben.fit(df_1['price_category'])
df_1['price_category'] = lben.transform(df_1['price_category'])

In [ ]:
df_1['price_category'].value_counts()

price_category
0    3495
2    3280
1    3225
Name: count, dtype: int64

In [ ]:
lben = LabelEncoder()

In [ ]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,0,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,2,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,0,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,2,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,2,2021-05-03 22:32:06+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002.0,toyota,rav4,gas,150000,clean,automatic,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,1,2021-04-10 20:33:57+00:00
9996,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008.0,jeep,wrangler,gas,113573,clean,other,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,2,2021-05-03 13:36:30+00:00
9997,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011.0,audi,a3 2.0t premium plus pzev,gas,150184,clean,automatic,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,1,2021-04-22 19:14:01+00:00
9998,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015.0,porsche,cayenne,hybrid,61943,clean,automatic,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,0,2021-04-14 14:14:42+00:00
9999,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017.0,ram,1500 crew cab big horn,gas,35921,clean,other,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,0,2021-04-24 17:50:49+00:00

In [ ]:
lben

LabelEncoder()

In [ ]:
df_1['title_status'].value_counts()

title_status
clean         9320
rebuilt        168
other          146
salvage         91
lien            35
missing         16
parts only       2
Name: count, dtype: int64

In [ ]:
lben.fit(df_1['title_status'])
df_1['title_status'] = lben.transform(df_1['title_status'])
df_1['title_status'].value_counts()

title_status
0    9320
5     168
3     146
6      91
1      35
2      16
4       2
Name: count, dtype: int64

In [ ]:
df_1['fuel'].value_counts()

fuel
gas         8402
other        730
diesel       653
hybrid       108
electric      44
Name: count, dtype: int64

In [ ]:
lben.fit(df_1['fuel'])
df_1['fuel'] = lben.transform(df_1['fuel'])
df_1['fuel'].value_counts()

fuel
2    8402
4     730
0     653
3     108
5      63
1      44
Name: count, dtype: int64

In [ ]:
df_1['fuel'] = lben.inverse_transform(df_1['fuel'])
df_1['fuel'].value_counts()

fuel
gas         8402
other        730
diesel       653
hybrid       108
electric      44
Name: count, dtype: int64

In [ ]:
df_1['transmission'].value_counts()

transmission
automatic    7534
other        1621
manual        623
Name: count, dtype: int64

In [ ]:
lben.fit(df_1['transmission'])
df_1['transmission'] = lben.transform(df_1['transmission'])
df_1['transmission'].value_counts()

transmission
0    7534
2    1621
1     623
Name: count, dtype: int64

**One Hot Encoder**

In [31]:
df_1['fuel'].value_counts(dropna = False)

fuel
gas         8268
other        722
diesel       642
hybrid       103
electric      43
Name: count, dtype: int64

In [ ]:
df_1.shape

(9778, 20)

In [33]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

ohe.fit(df_1[['fuel']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [34]:
ohe.transform(df_1[['fuel']]).shape

(9778, 5)

In [20]:
'is_' + ohe.get_feature_names_out()

array(['is_fuel_diesel', 'is_fuel_electric', 'is_fuel_gas',
       'is_fuel_hybrid', 'is_fuel_other'], dtype=object)

In [35]:
is_fuel = pd.DataFrame(ohe.transform(df_1[['fuel']]), columns = 'is_' + ohe.get_feature_names_out())

In [38]:
is_fuel.isna().sum()

is_fuel_diesel      0
is_fuel_electric    0
is_fuel_gas         0
is_fuel_hybrid      0
is_fuel_other       0
dtype: int64

In [39]:
is_fuel

,is_fuel_diesel,is_fuel_electric,is_fuel_gas,is_fuel_hybrid,is_fuel_other
0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...
9773,0.0,0.0,1.0,0.0,0.0
9774,0.0,0.0,1.0,0.0,0.0
9775,0.0,0.0,1.0,0.0,0.0
9776,0.0,0.0,0.0,1.0,0.0
9777,0.0,0.0,1.0,0.0,0.0

In [42]:
df_1.reset_index(inplace = True)

In [44]:
df_1.drop(columns = 'index', inplace = True)

In [36]:
df_1.isna().sum()

id                0
url               0
region            0
region_url        0
price             0
year              0
manufacturer      0
model             0
fuel              0
odometer          0
title_status      0
transmission      0
image_url         0
description       0
state             0
lat               0
long              0
posting_date      0
price_category    0
date              0
dtype: int64

In [45]:
df_1 =  pd.concat([df_1, is_fuel], axis = 1)
df_1 = df_1.drop(columns=['fuel'])

In [46]:
df_1.isna().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
odometer            0
title_status        0
transmission        0
image_url           0
description         0
state               0
lat                 0
long                0
posting_date        0
price_category      0
date                0
is_fuel_diesel      0
is_fuel_electric    0
is_fuel_gas         0
is_fuel_hybrid      0
is_fuel_other       0
dtype: int64

In [70]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,odometer,title_status,...,lat,long,posting_date,price_category,date,is_fuel_diesel,is_fuel_electric,is_fuel_gas,is_fuel_hybrid,is_fuel_other
0,7.308295e+09,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990.0,2020.0,ram,2500 crew cab big horn,27442.0,clean,...,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00,1.0,0.0,0.0,0.0,0.0
2,7.313734e+09,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590.0,2017.0,volkswagen,golf r hatchback,14048.0,clean,...,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00,0.0,0.0,1.0,0.0,0.0
3,7.308211e+09,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500.0,2013.0,toyota,rav4,117291.0,clean,...,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00,0.0,0.0,1.0,0.0,0.0
4,7.316475e+09,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800.0,2021.0,nissan,altima,8000.0,clean,...,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00,0.0,0.0,0.0,0.0,1.0
5,7.303797e+09,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590.0,2012.0,bmw,1 series 128i coupe 2d,80465.0,clean,...,35.970000,-83.940000,2021-04-08T15:10:56-0400,medium,2021-04-08 19:10:56+00:00,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0
9650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0
9668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0
9723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0
9725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0

In [71]:
ohe_title_status = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

ohe_title_status.fit(df_1[['title_status']])
is_title_status = pd.DataFrame(ohe_title_status.transform(df_1[['title_status']]), columns = 'is_' + ohe_title_status.get_feature_names_out())

In [ ]:
df_1 =  pd.concat([df_1, is_title_status], axis=1)
df_1 = df_1.drop(columns=['title_status'])

In [73]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,odometer,transmission,...,is_fuel_hybrid,is_fuel_other,is_title_status_clean,is_title_status_lien,is_title_status_missing,is_title_status_other,is_title_status_parts only,is_title_status_rebuilt,is_title_status_salvage,is_title_status_nan
0,7.308295e+09,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990.0,2020.0,ram,2500 crew cab big horn,27442.0,other,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7.313734e+09,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590.0,2017.0,volkswagen,golf r hatchback,14048.0,other,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7.308211e+09,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500.0,2013.0,toyota,rav4,117291.0,automatic,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7.316475e+09,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800.0,2021.0,nissan,altima,8000.0,automatic,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,7.303797e+09,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590.0,2012.0,bmw,1 series 128i coupe 2d,80465.0,other,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [74]:
ohe_transmission = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

ohe_transmission.fit(df_1[['transmission']])
is_transmission = pd.DataFrame(ohe_transmission.transform(df_1[['transmission']]), columns = 'is_' + ohe_transmission.get_feature_names_out())

In [75]:
df_1 =  pd.concat([df_1, is_transmission], axis=1)
df_1 = df_1.drop(columns=['transmission'])

In [76]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,odometer,image_url,...,is_title_status_missing,is_title_status_other,is_title_status_parts only,is_title_status_rebuilt,is_title_status_salvage,is_title_status_nan,is_transmission_automatic,is_transmission_manual,is_transmission_other,is_transmission_nan
0,7.308295e+09,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990.0,2020.0,ram,2500 crew cab big horn,27442.0,https://images.craigslist.org/00N0N_1xMPvfxRAI...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,7.313734e+09,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590.0,2017.0,volkswagen,golf r hatchback,14048.0,https://images.craigslist.org/00y0y_eeZjWeiSfb...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,7.308211e+09,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500.0,2013.0,toyota,rav4,117291.0,https://images.craigslist.org/00606_iGe5iXidib...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,7.316475e+09,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800.0,2021.0,nissan,altima,8000.0,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,7.303797e+09,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590.0,2012.0,bmw,1 series 128i coupe 2d,80465.0,https://images.craigslist.org/00F0F_5UAXmOzC18...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [80]:
df_1_copy = df_1.copy()
for i in df_1_copy:
    df_1 = df_1.dropna(subset=[i])
df_1

,id,url,region,region_url,price,year,manufacturer,model,odometer,image_url,...,is_title_status_missing,is_title_status_other,is_title_status_parts only,is_title_status_rebuilt,is_title_status_salvage,is_title_status_nan,is_transmission_automatic,is_transmission_manual,is_transmission_other,is_transmission_nan
0,7.308295e+09,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990.0,2020.0,ram,2500 crew cab big horn,27442.0,https://images.craigslist.org/00N0N_1xMPvfxRAI...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,7.313734e+09,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590.0,2017.0,volkswagen,golf r hatchback,14048.0,https://images.craigslist.org/00y0y_eeZjWeiSfb...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,7.308211e+09,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500.0,2013.0,toyota,rav4,117291.0,https://images.craigslist.org/00606_iGe5iXidib...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,7.316475e+09,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800.0,2021.0,nissan,altima,8000.0,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,7.303797e+09,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590.0,2012.0,bmw,1 series 128i coupe 2d,80465.0,https://images.craigslist.org/00F0F_5UAXmOzC18...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9773,7.301833e+09,https://harrisonburg.craigslist.org/cto/d/mc-g...,harrisonburg,https://harrisonburg.craigslist.org,8394.0,2007.0,ford,mustang,152000.0,https://images.craigslist.org/00909_3zQ3YPJB9Q...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9774,7.313042e+09,https://santabarbara.craigslist.org/ctd/d/oran...,santa barbara,https://santabarbara.craigslist.org,13997.0,2005.0,audi,q7,119500.0,https://images.craigslist.org/00101_kO6tRRh2BE...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9775,7.303557e+09,https://bozeman.craigslist.org/cto/d/bozeman-2...,bozeman,https://bozeman.craigslist.org,14500.0,2015.0,mercedes-benz,ml350 4matic,144000.0,https://images.craigslist.org/00n0n_6bESwEbAIG...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9776,7.316391e+09,https://tampa.craigslist.org/psc/ctd/d/hudson-...,tampa bay area,https://tampa.craigslist.org,3900.0,2011.0,nissan,versa,160000.0,https://images.craigslist.org/01515_jIRkuaHOUN...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9777,7.314027e+09,https://tulsa.craigslist.org/ctd/d/woodward-20...,tulsa,https://tulsa.craigslist.org,13995.0,2015.0,jeep,grand cherokee laredo 4x4 1owner well maint*ne...,141383.0,https://images.craigslist.org/00P0P_jD8VAvrIvV...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [81]:
df_1 = df_1.drop(columns=['is_transmission_nan'])
df_1 = df_1.drop(columns=['is_title_status_nan'])

In [82]:
df_1

,id,url,region,region_url,price,year,manufacturer,model,odometer,image_url,...,is_title_status_clean,is_title_status_lien,is_title_status_missing,is_title_status_other,is_title_status_parts only,is_title_status_rebuilt,is_title_status_salvage,is_transmission_automatic,is_transmission_manual,is_transmission_other
0,7.308295e+09,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990.0,2020.0,ram,2500 crew cab big horn,27442.0,https://images.craigslist.org/00N0N_1xMPvfxRAI...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7.313734e+09,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590.0,2017.0,volkswagen,golf r hatchback,14048.0,https://images.craigslist.org/00y0y_eeZjWeiSfb...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,7.308211e+09,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500.0,2013.0,toyota,rav4,117291.0,https://images.craigslist.org/00606_iGe5iXidib...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,7.316475e+09,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800.0,2021.0,nissan,altima,8000.0,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,7.303797e+09,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590.0,2012.0,bmw,1 series 128i coupe 2d,80465.0,https://images.craigslist.org/00F0F_5UAXmOzC18...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9773,7.301833e+09,https://harrisonburg.craigslist.org/cto/d/mc-g...,harrisonburg,https://harrisonburg.craigslist.org,8394.0,2007.0,ford,mustang,152000.0,https://images.craigslist.org/00909_3zQ3YPJB9Q...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9774,7.313042e+09,https://santabarbara.craigslist.org/ctd/d/oran...,santa barbara,https://santabarbara.craigslist.org,13997.0,2005.0,audi,q7,119500.0,https://images.craigslist.org/00101_kO6tRRh2BE...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9775,7.303557e+09,https://bozeman.craigslist.org/cto/d/bozeman-2...,bozeman,https://bozeman.craigslist.org,14500.0,2015.0,mercedes-benz,ml350 4matic,144000.0,https://images.craigslist.org/00n0n_6bESwEbAIG...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9776,7.316391e+09,https://tampa.craigslist.org/psc/ctd/d/hudson-...,tampa bay area,https://tampa.craigslist.org,3900.0,2011.0,nissan,versa,160000.0,https://images.craigslist.org/01515_jIRkuaHOUN...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9777,7.314027e+09,https://tulsa.craigslist.org/ctd/d/woodward-20...,tulsa,https://tulsa.craigslist.org,13995.0,2015.0,jeep,grand cherokee laredo 4x4 1owner well maint*ne...,141383.0,https://images.craigslist.org/00P0P_jD8VAvrIvV...,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0